"""Convert pipeline JSON reports to SQL INSERT statements for database seeding.

Usage:
    python -m scripts.export_to_sql \\
        /tmp/guangxi_auto.json /tmp/wc_auto.json /tmp/gold_auto.json /tmp/missile_auto.json \\
        --output seed_data.sql
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime
from pathlib import Path


def _esc(v) -> str:
    if v is None:
        return "NULL"
    if isinstance(v, bool):
        return "1" if v else "0"
    if isinstance(v, (int, float)):
        return str(v)
    return "'" + str(v).replace("'", "''").replace("\\", "\\\\") + "'"


def _dt(s) -> str:
    if not s:
        return "NULL"
    try:
        dt = datetime.fromisoformat(str(s).replace("T12:00:00", " 12:00:00"))
        return f"'{dt.strftime('%Y-%m-%d %H:%M:%S')}'"
    except Exception:
        return _esc(s)


def report_to_sql(report: dict, event_id: int) -> list[str]:
    stmts = []
    lc = report.get("lifecycle", {})
    sp = lc.get("stage_probability", {})
    sentiment = report.get("sentiment", {})

    cols = (
        "event_id, title, heat, report_count, duplicate_count, "
        "time_start, time_end, event_time, risk_level, stage, confidence, "
        "prob_latent, prob_growth, prob_peak, prob_decline, analysis, "
        "positive, neutral, negative, sources, "
        "summary, location, cause, people, authenticity, propagation, "
        "created_at, updated_at"
    )
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    people = report.get("people")
    authenticity = report.get("authenticity")
    propagation = report.get("propagation")
    vals = ", ".join([
        str(event_id),
        _esc(report.get("title", "")),
        _esc(report.get("heat", 0)),
        _esc(report.get("report_count", 0)),
        _esc(report.get("duplicate_count", 0)),
        _dt(report.get("time_start")),
        _dt(report.get("time_end")),
        _dt(report.get("event_time")),
        _esc(report.get("risk_level")),
        _esc(lc.get("stage") or report.get("stage")),
        _esc(lc.get("confidence") or report.get("confidence", 0)),
        _esc(sp.get("latent", 0)),
        _esc(sp.get("growth", 0)),
        _esc(sp.get("peak", 0)),
        _esc(sp.get("decline", 0)),
        _esc(lc.get("analysis") or report.get("analysis")),
        _esc(sentiment.get("positive", 0)),
        _esc(sentiment.get("neutral", 0)),
        _esc(sentiment.get("negative", 0)),
        _esc(json.dumps(report.get("sources", []), ensure_ascii=False)),
        _esc(report.get("summary")),
        _esc(report.get("location")),
        _esc(report.get("cause")),
        _esc(json.dumps(people, ensure_ascii=False)) if people else "NULL",
        _esc(json.dumps(authenticity, ensure_ascii=False)) if authenticity else "NULL",
        _esc(json.dumps(propagation, ensure_ascii=False)) if propagation else "NULL",
        f"'{now}'",
        f"'{now}'",
    ])
    stmts.append(f"INSERT INTO events ({cols}) VALUES ({vals});")

    for rank, kw in enumerate(report.get("keywords", [])):
        stmts.append(
            f"INSERT INTO event_keywords (event_id, word, weight, rank) "
            f"VALUES ({event_id}, {_esc(kw['word'])}, {_esc(kw['weight'])}, {rank});"
        )

    for rank, pf in enumerate(report.get("platform_distribution", [])):
        stmts.append(
            f"INSERT INTO event_platforms (event_id, platform_name, ratio, rank) "
            f"VALUES ({event_id}, {_esc(pf['platform_name'])}, {_esc(pf['ratio'])}, {rank});"
        )

    for d in report.get("trend", []):
        stmts.append(
            f"INSERT INTO event_trend_daily (event_id, date, count, is_predicted) "
            f"VALUES ({event_id}, {_esc(d['date'])}, {_esc(d['count'])}, 0);"
        )

    for d in lc.get("future_trend", []):
        stmts.append(
            f"INSERT INTO event_trend_daily "
            f"(event_id, date, count, is_predicted, predict_heat, predict_count) "
            f"VALUES ({event_id}, {_esc(d.get('date'))}, 0, 1, "
            f"{_esc(d.get('predict_heat'))}, {_esc(d.get('predict_count'))});"
        )

    return stmts


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("files", nargs="+", type=Path, help="pipeline JSON report files")
    parser.add_argument("--output", type=Path, default=Path("seed_data.sql"))
    parser.add_argument("--min-heat", type=float, default=5.0, help="skip clusters below this heat (default 5.0)")
    args = parser.parse_args()

    lines = [
        "-- Trendsight seed data — generated by scripts/export_to_sql.py",
        f"-- Generated at: {datetime.now().isoformat()}",
        "SET NAMES utf8mb4;",
        "",
    ]

    event_id = 1
    for path in args.files:
        with path.open(encoding="utf-8") as f:
            reports = json.load(f)
        kept = [r for r in reports if r.get("heat", 0) >= args.min_heat]
        lines.append(f"-- {path.name}: {len(kept)}/{len(reports)} clusters (heat >= {args.min_heat})")
        for report in kept:
            lines.extend(report_to_sql(report, event_id))
            lines.append("")
            event_id += 1

    args.output.write_text("\n".join(lines), encoding="utf-8")
    print(f"写入 {event_id - 1} 个事件 → {args.output}")


if __name__ == "__main__":
    main()
